/* ============================================================
   STORY & VOCABULARY DATA — the only file you need to edit!

   Each word looks like:
     { hanzi: '狗', pinyin: 'gǒu', en: 'dog', emoji: '🐶', also: ['够'] }

   - hanzi  : what the speech recognizer should hear (Chinese characters)
   - pinyin : shown big on screen (kids read this)
   - en     : small English hint
   - emoji  : the picture
   - also   : EXTRA ACCEPTED ANSWERS. The recognizer often mis-hears kids —
              open the browser console (F12) while she plays and watch the
              lines that start with [heard]. If her good attempts show up as
              a different character (e.g. 妈 when she said 马), add that
              character here and the game will accept it next time!

   Each chapter also has a "finale" — a short magic phrase using words she
   just practiced. bg is the scene's background gradient, deco is the
   scenery emoji, sticker is the reward for finishing the chapter.
   ============================================================ */

window.STORIES = [

  /* ==================== STORY 1: RED PANDY ==================== */
  {
    id: 'panda',
    title: '红熊猫回家',
    titleEn: 'Red Pandy Goes Home',
    tagline: 'Red Pandy is lost! Speak Chinese to help her travel home to Bamboo Mountain.',
    // img: a picture file in this folder used instead of the emoji everywhere
    hero: { name: '红熊猫', emoji: '🦝', img: 'redpanda icon.png' },
    ending: { zh: '红熊猫到家了！谢谢你！', en: 'Red Pandy made it home! The whole red panda family is together again — thanks to YOU!', audioZh: 'audio/panda/ending-panda.wav' },
    chapters: [
      {
        id: 'panda-greetings',
        title: '你好村', titleEn: 'Hello Village', emoji: '🏡', sticker: '👋',
        bg: 'linear-gradient(180deg,#aee9ff,#d4f7c5)', deco: '🏡🌳',
        intro: { en: 'Red Pandy meets friendly villagers! Say hello in Chinese to make friends for her.', zh: '红熊猫遇到了友好的村民！说你好，帮她交朋友吧！', audioZh: 'audio/panda/intro-panda-greetings.wav' },
        audioComplete: 'audio/panda/complete-panda-greetings.wav',
        words: [
          { hanzi: '你好', pinyin: 'nǐ hǎo', en: 'hello', emoji: '👋', also: [], audioZh: 'audio/panda/ni-hao.wav' },
          { hanzi: '谢谢', pinyin: 'xiè xie', en: 'thank you', emoji: '🙏', also: [], audioZh: 'audio/panda/xie-xie.wav' },
          { hanzi: '再见', pinyin: 'zài jiàn', en: 'goodbye', emoji: '🫡', also: ['在见'], audioZh: 'audio/panda/zai-jian.wav' },
          { hanzi: '请', pinyin: 'qǐng', en: 'please', emoji: '🤲', also: ['清', '情', '青'], audioZh: 'audio/panda/qing.wav' },
          { hanzi: '好', pinyin: 'hǎo', en: 'good / OK', emoji: '👍', also: ['号', '郝'], audioZh: 'audio/panda/hao.wav' },
          { hanzi: '我是红熊猫', pinyin: 'wǒ shì hóng xióng māo', en: 'I am Red Pandy', emoji: '🦝', img: 'redpanda icon.png', also: ['红熊猫', '熊猫', '我是', '红'], audioZh: 'audio/panda/wo-shi-hong-xiong-mao.wav' },
        ],
        finale: { hanzi: '你好，谢谢你！', pinyin: 'nǐ hǎo, xiè xie nǐ!', en: 'Hello, thank you!', emoji: '🎉', also: ['你好', '谢谢'], audioZh: 'audio/panda/finale-panda-greetings.wav' },
      },
      {
        id: 'panda-animals',
        title: '快乐农场', titleEn: 'Happy Farm', emoji: '🚜', sticker: '🐶',
        bg: 'linear-gradient(180deg,#bfe9ff,#f5e5a3)', deco: '🚜🌾',
        intro: { en: 'The farm animals are hiding in the barn! Call their names in Chinese and they will come out to play.', zh: '小动物们躲在谷仓里！叫它们的名字，它们就会出来玩！', audioZh: 'audio/panda/intro-panda-animals.wav' },
        audioComplete: 'audio/panda/complete-panda-animals.wav',
        words: [
          { hanzi: '狗', pinyin: 'gǒu', en: 'dog', emoji: '🐶', also: ['够'], audioZh: 'audio/panda/gou.wav' },
          { hanzi: '猫', pinyin: 'māo', en: 'cat', emoji: '🐱', also: ['毛', '帽'], audioZh: 'audio/panda/mao.wav' },
          { hanzi: '鸡', pinyin: 'jī', en: 'chicken', emoji: '🐔', also: ['机', '几', '急'], audioZh: 'audio/panda/ji.wav' },
          { hanzi: '鸭子', pinyin: 'yā zi', en: 'duck', emoji: '🦆', also: ['鸭', '压'], audioZh: 'audio/panda/ya-zi.wav' },
          { hanzi: '马', pinyin: 'mǎ', en: 'horse', emoji: '🐴', also: ['妈', '吗', '码'], audioZh: 'audio/panda/ma.wav' },
          { hanzi: '牛', pinyin: 'niú', en: 'cow', emoji: '🐮', also: ['纽'], audioZh: 'audio/panda/niu.wav' },
          { hanzi: '猪', pinyin: 'zhū', en: 'pig', emoji: '🐷', also: ['珠', '朱', '住'], audioZh: 'audio/panda/zhu.wav' },
          { hanzi: '羊', pinyin: 'yáng', en: 'sheep', emoji: '🐑', also: ['阳', '洋', '样'], audioZh: 'audio/panda/yang.wav' },
        ],
        finale: { hanzi: '我爱小狗！', pinyin: 'wǒ ài xiǎo gǒu!', en: 'I love the puppy!', emoji: '🥰', also: ['小狗', '我爱'], audioZh: 'audio/panda/finale-panda-animals.wav' },
      },
      {
        id: 'panda-colors',
        title: '彩虹桥', titleEn: 'Rainbow Bridge', emoji: '🌈', sticker: '🌈',
        bg: 'linear-gradient(180deg,#c8ecff,#e8d5ff)', deco: '🌈☁️',
        intro: { en: 'The rainbow bridge lost its colors! Say each color in Chinese to paint it back so Red Pandy can cross.', zh: '彩虹桥没有颜色了！说出每个颜色，把桥画回来，红熊猫才能过桥！', audioZh: 'audio/panda/intro-panda-colors.wav' },
        audioComplete: 'audio/panda/complete-panda-colors.wav',
        words: [
          { hanzi: '红色', pinyin: 'hóng sè', en: 'red', emoji: '❤️', also: ['红'], audioZh: 'audio/panda/hong-se.wav' },
          { hanzi: '橙色', pinyin: 'chéng sè', en: 'orange', emoji: '🧡', also: ['橙', '成色'], audioZh: 'audio/panda/cheng-se.wav' },
          { hanzi: '黄色', pinyin: 'huáng sè', en: 'yellow', emoji: '💛', also: ['黄'], audioZh: 'audio/panda/huang-se.wav' },
          { hanzi: '绿色', pinyin: 'lǜ sè', en: 'green', emoji: '💚', also: ['绿'], audioZh: 'audio/panda/lv-se.wav' },
          { hanzi: '蓝色', pinyin: 'lán sè', en: 'blue', emoji: '💙', also: ['蓝', '兰色'], audioZh: 'audio/panda/lan-se.wav' },
          { hanzi: '紫色', pinyin: 'zǐ sè', en: 'purple', emoji: '💜', also: ['紫', '子色'], audioZh: 'audio/panda/zi-se.wav' },
          { hanzi: '粉色', pinyin: 'fěn sè', en: 'pink', emoji: '🩷', also: ['粉', '分色'], audioZh: 'audio/panda/fen-se.wav' },
        ],
        finale: { hanzi: '我喜欢红色！', pinyin: 'wǒ xǐ huan hóng sè!', en: 'I like red!', emoji: '😍', also: ['喜欢', '红色'], audioZh: 'audio/panda/finale-panda-colors.wav' },
      },
      {
        id: 'panda-numbers',
        title: '数字河', titleEn: 'Number River', emoji: '🌊', sticker: '🔟',
        bg: 'linear-gradient(180deg,#b3e5fc,#81d4fa)', deco: '🌊🐟',
        intro: { en: 'Red Pandy must cross the river! Count in Chinese — every number makes a stepping stone appear.', zh: '红熊猫要过河！一起数数，每个数字都会变出一块踏脚石！', audioZh: 'audio/panda/intro-panda-numbers.wav' },
        audioComplete: 'audio/panda/complete-panda-numbers.wav',
        words: [
          { hanzi: '一', pinyin: 'yī', en: 'one', emoji: '1️⃣', also: ['1', '衣', '医'], audioZh: 'audio/panda/yi.wav' },
          { hanzi: '二', pinyin: 'èr', en: 'two', emoji: '2️⃣', also: ['2', '儿'], audioZh: 'audio/panda/er.wav' },
          { hanzi: '三', pinyin: 'sān', en: 'three', emoji: '3️⃣', also: ['3', '山', '伞'], audioZh: 'audio/panda/san.wav' },
          { hanzi: '四', pinyin: 'sì', en: 'four', emoji: '4️⃣', also: ['4', '是', '事'], audioZh: 'audio/panda/si.wav' },
          { hanzi: '五', pinyin: 'wǔ', en: 'five', emoji: '5️⃣', also: ['5', '舞', '午'], audioZh: 'audio/panda/wu.wav' },
          { hanzi: '六', pinyin: 'liù', en: 'six', emoji: '6️⃣', also: ['6', '留', '流'], audioZh: 'audio/panda/liu.wav' },
          { hanzi: '七', pinyin: 'qī', en: 'seven', emoji: '7️⃣', also: ['7', '气', '期'], audioZh: 'audio/panda/qi.wav' },
          { hanzi: '八', pinyin: 'bā', en: 'eight', emoji: '8️⃣', also: ['8', '吧', '爸'], audioZh: 'audio/panda/ba.wav' },
          { hanzi: '九', pinyin: 'jiǔ', en: 'nine', emoji: '9️⃣', also: ['9', '酒', '就'], audioZh: 'audio/panda/jiu.wav' },
          { hanzi: '十', pinyin: 'shí', en: 'ten', emoji: '🔟', also: ['10', '时', '石'], audioZh: 'audio/panda/shi.wav' },
        ],
        finale: { hanzi: '一二三，跳！', pinyin: 'yī èr sān, tiào!', en: '1, 2, 3, jump!', emoji: '🦘', also: ['一二三', '123', '跳'], audioZh: 'audio/panda/finale-panda-numbers.wav' },
      },
      {
        id: 'panda-food',
        title: '大市场', titleEn: 'Big Market', emoji: '🧺', sticker: '🍎',
        bg: 'linear-gradient(180deg,#ffe0b2,#ffccbc)', deco: '🏪🍉',
        intro: { en: 'Red Pandy is SO hungry! Order yummy food in Chinese to fill her picnic basket.', zh: '红熊猫好饿呀！点好吃的，装满她的野餐篮子！', audioZh: 'audio/panda/intro-panda-food.wav' },
        audioComplete: 'audio/panda/complete-panda-food.wav',
        words: [
          { hanzi: '苹果', pinyin: 'píng guǒ', en: 'apple', emoji: '🍎', also: ['苹', '平果'], audioZh: 'audio/panda/ping-guo.wav' },
          { hanzi: '香蕉', pinyin: 'xiāng jiāo', en: 'banana', emoji: '🍌', also: ['香', '蕉'], audioZh: 'audio/panda/xiang-jiao.wav' },
          { hanzi: '西瓜', pinyin: 'xī guā', en: 'watermelon', emoji: '🍉', also: ['西', '瓜'], audioZh: 'audio/panda/xi-gua.wav' },
          { hanzi: '米饭', pinyin: 'mǐ fàn', en: 'rice', emoji: '🍚', also: ['米', '饭'], audioZh: 'audio/panda/mi-fan.wav' },
          { hanzi: '面条', pinyin: 'miàn tiáo', en: 'noodles', emoji: '🍜', also: ['面', '条'], audioZh: 'audio/panda/mian-tiao.wav' },
          { hanzi: '包子', pinyin: 'bāo zi', en: 'steamed bun', emoji: '🥟', also: ['包', '抱'], audioZh: 'audio/panda/bao-zi.wav' },
          { hanzi: '牛奶', pinyin: 'niú nǎi', en: 'milk', emoji: '🥛', also: ['牛', '奶'], audioZh: 'audio/panda/niu-nai.wav' },
          { hanzi: '水', pinyin: 'shuǐ', en: 'water', emoji: '💧', also: ['谁', '睡'], audioZh: 'audio/panda/shui.wav' },
        ],
        finale: { hanzi: '我要苹果，谢谢！', pinyin: 'wǒ yào píng guǒ, xiè xie!', en: 'I want an apple, thank you!', emoji: '😋', also: ['苹果', '我要'], audioZh: 'audio/panda/finale-panda-food.wav' },
      },
      {
        id: 'panda-weather',
        title: '天气山', titleEn: 'Weather Mountain', emoji: '⛰️', sticker: '☀️',
        bg: 'linear-gradient(180deg,#90caf9,#e1f5fe)', deco: '⛰️☁️',
        intro: { en: 'The mountain weather is going wild! Say the weather words in Chinese to calm the sky.', zh: '山上的天气变来变去！说出天气词，让天空安静下来！', audioZh: 'audio/panda/intro-panda-weather.wav' },
        audioComplete: 'audio/panda/complete-panda-weather.wav',
        words: [
          { hanzi: '太阳', pinyin: 'tài yáng', en: 'sun', emoji: '☀️', also: ['太', '阳'], audioZh: 'audio/panda/tai-yang.wav' },
          { hanzi: '下雨', pinyin: 'xià yǔ', en: 'raining', emoji: '🌧️', also: ['雨'], audioZh: 'audio/panda/xia-yu.wav' },
          { hanzi: '下雪', pinyin: 'xià xuě', en: 'snowing', emoji: '❄️', also: ['雪'], audioZh: 'audio/panda/xia-xue.wav' },
          { hanzi: '云', pinyin: 'yún', en: 'cloud', emoji: '☁️', also: ['运', '晕'], audioZh: 'audio/panda/yun.wav' },
          { hanzi: '风', pinyin: 'fēng', en: 'wind', emoji: '💨', also: ['封', '疯', '丰'], audioZh: 'audio/panda/feng.wav' },
          { hanzi: '热', pinyin: 'rè', en: 'hot', emoji: '🥵', also: ['乐', '日'], audioZh: 'audio/panda/re.wav' },
          { hanzi: '冷', pinyin: 'lěng', en: 'cold', emoji: '🥶', also: ['愣'], audioZh: 'audio/panda/leng.wav' },
        ],
        finale: { hanzi: '今天太阳出来了！', pinyin: 'jīn tiān tài yáng chū lái le!', en: 'The sun came out today!', emoji: '🌞', also: ['太阳', '出来了', '今天'], audioZh: 'audio/panda/finale-panda-weather.wav' },
      },
      {
        id: 'panda-describe',
        title: '描述一下', titleEn: 'Describe It', emoji: '🔍', sticker: '🖼️',
        bg: 'linear-gradient(180deg,#d7f0ff,#ffe9c7)', deco: '🔍🌼',
        intro: { en: 'On the way home, Red Pandy sees so many things! Describe them in Chinese — now with two words together.', zh: '回家的路上，红熊猫看到好多东西！用中文说一说，这次要说两个词哦！', audioZh: 'audio/panda/intro-panda-describe.wav' },
        audioComplete: 'audio/panda/complete-panda-describe.wav',
        words: [
          { hanzi: '大狗', pinyin: 'dà gǒu', en: 'big dog', emoji: '🐕', also: ['狗', '大'], audioZh: 'audio/panda/da-gou.wav' },
          { hanzi: '小猫', pinyin: 'xiǎo māo', en: 'little cat', emoji: '🐱', also: ['猫', '小'], audioZh: 'audio/panda/xiao-mao.wav' },
          { hanzi: '红苹果', pinyin: 'hóng píng guǒ', en: 'red apple', emoji: '🍎', also: ['苹果', '红'], audioZh: 'audio/panda/hong-ping-guo.wav' },
          { hanzi: '大西瓜', pinyin: 'dà xī guā', en: 'big watermelon', emoji: '🍉', also: ['西瓜', '大'], audioZh: 'audio/panda/da-xi-gua.wav' },
          { hanzi: '白云', pinyin: 'bái yún', en: 'white cloud', emoji: '☁️', also: ['云', '白'], audioZh: 'audio/panda/bai-yun.wav' },
          { hanzi: '我的家', pinyin: 'wǒ de jiā', en: 'my home', emoji: '🏠', also: ['家', '我家'], audioZh: 'audio/panda/wo-de-jia.wav' },
        ],
        finale: { hanzi: '我有一只小狗！', pinyin: 'wǒ yǒu yì zhī xiǎo gǒu!', en: 'I have a little dog!', emoji: '🐶', also: ['小狗', '一只', '我有'], audioZh: 'audio/panda/finale-panda-describe.wav' },
      },
      {
        id: 'panda-family',
        title: '竹子山', titleEn: 'Bamboo Mountain', emoji: '🎋', sticker: '🏠',
        bg: 'linear-gradient(180deg,#c8e6c9,#a5d6a7)', deco: '🎋🎍',
        intro: { en: 'Red Pandy is home! Call each family member out of the bamboo for the biggest red panda hug ever.', zh: '红熊猫到家啦！把每个家人叫出来，抱一个大大的抱抱！', audioZh: 'audio/panda/intro-panda-family.wav' },
        audioComplete: 'audio/panda/complete-panda-family.wav',
        words: [
          { hanzi: '妈妈', pinyin: 'mā ma', en: 'mom', emoji: '👩', also: ['马', '吗'], audioZh: 'audio/panda/mama.wav' },
          { hanzi: '爸爸', pinyin: 'bà ba', en: 'dad', emoji: '👨', also: ['八', '吧'], audioZh: 'audio/panda/baba.wav' },
          { hanzi: '爷爷', pinyin: 'yé ye', en: 'grandpa', emoji: '👴', also: ['也', '叶'], audioZh: 'audio/panda/yeye.wav' },
          { hanzi: '奶奶', pinyin: 'nǎi nai', en: 'grandma', emoji: '👵', also: ['乃'], audioZh: 'audio/panda/nainai.wav' },
          { hanzi: '哥哥', pinyin: 'gē ge', en: 'big brother', emoji: '👦', also: ['歌', '格'], audioZh: 'audio/panda/gege.wav' },
          { hanzi: '妹妹', pinyin: 'mèi mei', en: 'little sister', emoji: '👧', also: ['美', '没'], audioZh: 'audio/panda/meimei.wav' },
          { hanzi: '家', pinyin: 'jiā', en: 'home / family', emoji: '🏠', also: ['加', '佳'], audioZh: 'audio/panda/jia.wav' },
        ],
        finale: { hanzi: '妈妈，我爱你！', pinyin: 'mā ma, wǒ ài nǐ!', en: 'Mom, I love you!', emoji: '💗', also: ['我爱你', '妈妈'], audioZh: 'audio/panda/finale-panda-family.wav' },
      },
      {
        id: 'panda-speaks',
        title: '红熊猫说话', titleEn: 'Red Pandy Speaks', emoji: '💬', sticker: '💬',
        bg: 'linear-gradient(180deg,#ffe0ec,#e5f5c7)', deco: '💬🌟',
        intro: { en: 'Sitting with her family, Red Pandy tells them all about her journey home — in whole sentences now. You can do it!', zh: '红熊猫和家人坐在一起，给大家讲她回家路上的故事——这次要说一整句话啦！你可以的！', audioZh: 'audio/panda/intro-panda-speaks.wav' },
        words: [
          { hanzi: '我爱吃苹果', pinyin: 'wǒ ài chī píng guǒ', en: 'I love eating apples', emoji: '🍎', also: ['苹果', '爱吃', '我爱'], audioZh: 'audio/panda/wo-ai-chi-ping-guo.wav' },
          { hanzi: '今天太阳很好', pinyin: 'jīn tiān tài yáng hěn hǎo', en: 'the sun is nice today', emoji: '☀️', also: ['太阳', '今天', '很好'], audioZh: 'audio/panda/jin-tian-tai-yang-hen-hao.wav' },
          { hanzi: '我有两个哥哥', pinyin: 'wǒ yǒu liǎng gè gē ge', en: 'I have two big brothers', emoji: '👦', also: ['哥哥', '两个', '我有'], audioZh: 'audio/panda/wo-you-liang-ge-ge-ge.wav' },
          { hanzi: '我要回家了', pinyin: 'wǒ yào huí jiā le', en: "I'm going home", emoji: '🏠', also: ['回家', '我要', '家'], audioZh: 'audio/panda/wo-yao-hui-jia-le.wav' },
          { hanzi: '妈妈在哪里', pinyin: 'mā ma zài nǎ lǐ', en: 'where is mom?', emoji: '👩', also: ['妈妈', '在哪', '哪里'], audioZh: 'audio/panda/ma-ma-zai-na-li.wav' },
        ],
        finale: { hanzi: '我到家了，我很开心！', pinyin: 'wǒ dào jiā le, wǒ hěn kāi xīn!', en: "I'm home, I'm so happy!", emoji: '🥰', also: ['到家', '开心', '我很'], audioZh: 'audio/panda/finale-panda-speaks.wav' },
      },
    ],
  },

  /* ==================== STORY 2: PUPPY RESCUE SQUAD ==================== */
  {
    id: 'pups',
    title: '汪汪救援队',
    titleEn: 'Puppy Rescue Squad',
    tagline: 'Fly with Skye! Speak Chinese to launch vehicles and save the day.',
    hero: { name: '天天', emoji: '🐕', img: 'Skye-thumbnail.png' },
    ending: { zh: '任务完成！天天和小猫都为你欢呼！你是真正的救援英雄！', en: 'Mission complete! The kitten is safe — Skye and the whole squad cheer for YOU!', audioZh: 'audio/pups/ending-pups.wav' },
    chapters: [
      {
        id: 'pups-hq',
        title: '救援基地', titleEn: 'Rescue HQ', emoji: '🗼', sticker: '📣',
        bg: 'linear-gradient(180deg,#b3e5fc,#ffe082)', deco: '🗼📡',
        intro: { en: 'Welcome to Rescue HQ! Skye is here to teach you the squad commands — every word makes a pup slide down the fire pole!', zh: '欢迎来到救援基地！天天教你小队口令，每说一个口令，就有一只小狗滑下消防杆！', audioZh: 'audio/pups/intro-pups-hq.wav' },
        audioComplete: 'audio/pups/complete-pups-hq.wav',
        words: [
          { hanzi: '你好', pinyin: 'nǐ hǎo', en: 'hello', emoji: '👋', also: [], audioZh: 'audio/pups/ni-hao.wav' },
          { hanzi: '出发', pinyin: 'chū fā', en: "let's roll!", emoji: '🚀', also: ['出', '发', '初发'], audioZh: 'audio/pups/chu-fa.wav' },
          { hanzi: '快', pinyin: 'kuài', en: 'fast!', emoji: '⚡', also: ['筷', '块'], audioZh: 'audio/pups/kuai.wav' },
          { hanzi: '帮忙', pinyin: 'bāng máng', en: 'help', emoji: '🤝', also: ['帮', '忙'], audioZh: 'audio/pups/bang-mang.wav' },
          { hanzi: '加油', pinyin: 'jiā yóu', en: 'go go go!', emoji: '💪', also: ['加', '油'], audioZh: 'audio/pups/jia-you.wav' },
          { hanzi: '汪汪', pinyin: 'wāng wāng', en: 'woof woof!', emoji: '🐶', also: ['王', '网', '汪'], audioZh: 'audio/pups/wang-wang.wav' },
        ],
        finale: { hanzi: '汪汪队，出发！', pinyin: 'wāng wāng duì, chū fā!', en: "Puppy squad, let's roll!", emoji: '🎖️', also: ['汪汪队', '出发', '汪汪'], audioZh: 'audio/pups/finale-pups-hq.wav' },
      },
      {
        id: 'pups-vehicles',
        title: '交通工具', titleEn: 'Vehicle Garage', emoji: '🚒', sticker: '🚒',
        bg: 'linear-gradient(180deg,#cfd8dc,#b0bec5)', deco: '🏁🔧',
        intro: { en: 'Time to launch the rescue vehicles! Name each one in Chinese and watch it zoom out of the garage.', zh: '该出动救援车啦！说出每辆车的名字，看它冲出车库！', audioZh: 'audio/pups/intro-pups-vehicles.wav' },
        audioComplete: 'audio/pups/complete-pups-vehicles.wav',
        words: [
          { hanzi: '车', pinyin: 'chē', en: 'car', emoji: '🚗', also: ['扯'], audioZh: 'audio/pups/che.wav' },
          { hanzi: '消防车', pinyin: 'xiāo fáng chē', en: 'fire truck', emoji: '🚒', also: ['消防'], audioZh: 'audio/pups/xiao-fang-che.wav' },
          { hanzi: '警车', pinyin: 'jǐng chē', en: 'police car', emoji: '🚓', also: ['警察'], audioZh: 'audio/pups/jing-che.wav' },
          { hanzi: '飞机', pinyin: 'fēi jī', en: 'airplane', emoji: '✈️', also: ['飞', '机'], audioZh: 'audio/pups/fei-ji.wav' },
          { hanzi: '直升机', pinyin: 'zhí shēng jī', en: 'helicopter', emoji: '🚁', also: ['直升'], audioZh: 'audio/pups/zhi-sheng-ji.wav' },
          { hanzi: '船', pinyin: 'chuán', en: 'boat', emoji: '🚤', also: ['穿', '传', '川'], audioZh: 'audio/pups/chuan.wav' },
          { hanzi: '自行车', pinyin: 'zì xíng chē', en: 'bicycle', emoji: '🚲', also: ['自行', '单车'], audioZh: 'audio/pups/zi-xing-che.wav' },
        ],
        finale: { hanzi: '我开消防车！', pinyin: 'wǒ kāi xiāo fáng chē!', en: "I'm driving the fire truck!", emoji: '🧑‍🚒', also: ['消防车', '我开'], audioZh: 'audio/pups/finale-pups-vehicles.wav' },
      },
      {
        id: 'pups-actions',
        title: '动作训练', titleEn: 'Action Training', emoji: '🏃', sticker: '🏅',
        bg: 'linear-gradient(180deg,#dcedc8,#aed581)', deco: '🚧🎯',
        intro: { en: 'Rescue pups need training! Shout each action in Chinese and Skye will do it.', zh: '救援小狗要训练！大声喊出动作，天天就会做！', audioZh: 'audio/pups/intro-pups-actions.wav' },
        audioComplete: 'audio/pups/complete-pups-actions.wav',
        words: [
          { hanzi: '跑', pinyin: 'pǎo', en: 'run', emoji: '🏃', also: ['袍', '抛'], audioZh: 'audio/pups/pao.wav' },
          { hanzi: '跳', pinyin: 'tiào', en: 'jump', emoji: '🦘', also: ['条', '调'], audioZh: 'audio/pups/tiao.wav' },
          { hanzi: '飞', pinyin: 'fēi', en: 'fly', emoji: '🕊️', also: ['非', '菲'], audioZh: 'audio/pups/fei.wav' },
          { hanzi: '游泳', pinyin: 'yóu yǒng', en: 'swim', emoji: '🏊', also: ['游', '泳'], audioZh: 'audio/pups/you-yong.wav' },
          { hanzi: '找', pinyin: 'zhǎo', en: 'find', emoji: '🔍', also: ['照', '赵'], audioZh: 'audio/pups/zhao.wav' },
          { hanzi: '救', pinyin: 'jiù', en: 'rescue', emoji: '🆘', also: ['就', '旧', '九'], audioZh: 'audio/pups/jiu.wav' },
          { hanzi: '停', pinyin: 'tíng', en: 'stop', emoji: '✋', also: ['听', '庭'], audioZh: 'audio/pups/ting.wav' },
        ],
        finale: { hanzi: '快跑，快跳！', pinyin: 'kuài pǎo, kuài tiào!', en: 'Run fast, jump high!', emoji: '💨', also: ['快跑', '快跳'], audioZh: 'audio/pups/finale-pups-actions.wav' },
      },
      {
        id: 'pups-city',
        title: '城市搜索', titleEn: 'City Search', emoji: '🗺️', sticker: '🐱',
        bg: 'linear-gradient(180deg,#e1f5fe,#ffe0e0)', deco: '🏙️🔦',
        intro: { en: 'A kitten is lost in the city! Say each place in Chinese to send Skye to search it. Where can she be?', zh: '小猫在城市里走丢了！说出每个地方，派天天去找一找。小猫会在哪里呢？', audioZh: 'audio/pups/intro-pups-city.wav' },
        audioComplete: 'audio/pups/complete-pups-city.wav',
        words: [
          { hanzi: '山', pinyin: 'shān', en: 'mountain', emoji: '⛰️', also: ['三', '衫'], audioZh: 'audio/pups/shan.wav' },
          { hanzi: '海', pinyin: 'hǎi', en: 'sea', emoji: '🌊', also: ['还', '嗨'], audioZh: 'audio/pups/hai.wav' },
          { hanzi: '学校', pinyin: 'xué xiào', en: 'school', emoji: '🏫', also: ['学', '校'], audioZh: 'audio/pups/xue-xiao.wav' },
          { hanzi: '商店', pinyin: 'shāng diàn', en: 'store', emoji: '🏪', also: ['商', '店'], audioZh: 'audio/pups/shang-dian.wav' },
          { hanzi: '家', pinyin: 'jiā', en: 'home', emoji: '🏠', also: ['加', '佳'], audioZh: 'audio/pups/jia.wav' },
          { hanzi: '公园', pinyin: 'gōng yuán', en: 'park', emoji: '🌳', also: ['公', '园'], audioZh: 'audio/pups/gong-yuan.wav' },
        ],
        finale: { hanzi: '小猫在公园！', pinyin: 'xiǎo māo zài gōng yuán!', en: 'The kitten is in the park!', emoji: '🐱', also: ['公园', '小猫'], audioZh: 'audio/pups/finale-pups-city.wav' },
      },
      {
        id: 'pups-rollout',
        title: '出动！', titleEn: 'Roll Out', emoji: '🛞', sticker: '🛞',
        bg: 'linear-gradient(180deg,#c8e6ff,#ffd9a8)', deco: '🛞💨',
        intro: { en: 'Put the words together! Say each action with its vehicle to roll the whole team out.', zh: '把词连起来！说出动作加交通工具，让全队一起出动！', audioZh: 'audio/pups/intro-pups-rollout.wav' },
        audioComplete: 'audio/pups/complete-pups-rollout.wav',
        words: [
          { hanzi: '开车', pinyin: 'kāi chē', en: 'drive a car', emoji: '🚗', also: ['车', '开'], audioZh: 'audio/pups/kai-che.wav' },
          { hanzi: '坐飞机', pinyin: 'zuò fēi jī', en: 'ride a plane', emoji: '✈️', also: ['飞机', '坐'], audioZh: 'audio/pups/zuo-fei-ji.wav' },
          { hanzi: '开消防车', pinyin: 'kāi xiāo fáng chē', en: 'drive the fire truck', emoji: '🚒', also: ['消防车', '开车'], audioZh: 'audio/pups/kai-xiao-fang-che.wav' },
          { hanzi: '快点跑', pinyin: 'kuài diǎn pǎo', en: 'run quickly', emoji: '🏃', also: ['快跑', '跑', '快点'], audioZh: 'audio/pups/kuai-dian-pao.wav' },
          { hanzi: '去救人', pinyin: 'qù jiù rén', en: 'go rescue', emoji: '🆘', also: ['救人', '救', '去'], audioZh: 'audio/pups/qu-jiu-ren.wav' },
          { hanzi: '上飞机', pinyin: 'shàng fēi jī', en: 'get on the plane', emoji: '🛫', also: ['飞机', '上'], audioZh: 'audio/pups/shang-fei-ji.wav' },
        ],
        finale: { hanzi: '我们开车去救援！', pinyin: 'wǒ men kāi chē qù jiù yuán!', en: "Let's drive to the rescue!", emoji: '🚗', also: ['开车', '救援', '我们'], audioZh: 'audio/pups/finale-pups-rollout.wav' },
      },
      {
        id: 'pups-where',
        title: '小猫在哪里？', titleEn: "Where's the Kitten", emoji: '🔦', sticker: '🔦',
        bg: 'linear-gradient(180deg,#e1f5fe,#f3e5ff)', deco: '🔦🐾',
        intro: { en: 'Search the city in full sentences! Tell the team where the lost kitten might be.', zh: '用整句话在城市里搜索！告诉大家小猫可能在哪里。', audioZh: 'audio/pups/intro-pups-where.wav' },
        audioComplete: 'audio/pups/complete-pups-where.wav',
        words: [
          { hanzi: '小猫在公园', pinyin: 'xiǎo māo zài gōng yuán', en: "the kitten's in the park", emoji: '🌳', also: ['公园', '小猫', '在'], audioZh: 'audio/pups/xiao-mao-zai-gong-yuan.wav' },
          { hanzi: '小猫在树上', pinyin: 'xiǎo māo zài shù shàng', en: "the kitten's up the tree", emoji: '🌲', also: ['树上', '小猫', '树'], audioZh: 'audio/pups/xiao-mao-zai-shu-shang.wav' },
          { hanzi: '快去找它', pinyin: 'kuài qù zhǎo tā', en: 'go find it fast', emoji: '🔍', also: ['找它', '找', '快去'], audioZh: 'audio/pups/kuai-qu-zhao-ta.wav' },
          { hanzi: '我看到它了', pinyin: 'wǒ kàn dào tā le', en: 'I see it!', emoji: '👀', also: ['看到', '看见', '它'], audioZh: 'audio/pups/wo-kan-dao-ta-le.wav' },
          { hanzi: '它在学校', pinyin: 'tā zài xué xiào', en: "it's at the school", emoji: '🏫', also: ['学校', '在'], audioZh: 'audio/pups/ta-zai-xue-xiao.wav' },
        ],
        finale: { hanzi: '我找到小猫了！', pinyin: 'wǒ zhǎo dào xiǎo māo le!', en: 'I found the kitten!', emoji: '🐱', also: ['找到', '小猫', '找'], audioZh: 'audio/pups/finale-pups-where.wav' },
      },
      {
        id: 'pups-radio',
        title: '对讲机', titleEn: 'Radio Call', emoji: '📻', sticker: '📻',
        bg: 'linear-gradient(180deg,#ffe082,#b3e5fc)', deco: '📻📡',
        intro: { en: 'Call the pups on the radio! Say each full-sentence order out loud.', zh: '用对讲机呼叫小狗们！大声说出每一句完整的命令。', audioZh: 'audio/pups/intro-pups-radio.wav' },
        audioComplete: 'audio/pups/complete-pups-radio.wav',
        words: [
          { hanzi: '阿奇，去公园！', pinyin: 'Ā qí, qù gōng yuán!', en: 'Chase, go to the park!', emoji: '🐕', also: ['阿奇', '公园', '去'], audioZh: 'audio/pups/a-qi-qu-gong-yuan.wav' },
          { hanzi: '天天，快飞！', pinyin: 'Tiān tiān, kuài fēi!', en: 'Skye, fly fast!', emoji: '🚁', also: ['天天', '快飞', '飞'], audioZh: 'audio/pups/tian-tian-kuai-fei.wav' },
          { hanzi: '毛毛，救小猫！', pinyin: 'Máo mao, jiù xiǎo māo!', en: 'Marshall, save the kitten!', emoji: '🐶', also: ['毛毛', '救', '小猫'], audioZh: 'audio/pups/mao-mao-jiu-xiao-mao.wav' },
          { hanzi: '我们出发吧！', pinyin: 'wǒ men chū fā ba!', en: "let's roll out!", emoji: '🚀', also: ['出发', '我们'], audioZh: 'audio/pups/wo-men-chu-fa-ba.wav' },
          { hanzi: '大家加油！', pinyin: 'dà jiā jiā yóu!', en: 'everyone, go go go!', emoji: '💪', also: ['加油', '大家'], audioZh: 'audio/pups/da-jia-jia-you.wav' },
        ],
        finale: { hanzi: '汪汪队，我们能行！', pinyin: 'wāng wāng duì, wǒ men néng xíng!', en: 'Puppy squad, we can do it!', emoji: '🎖️', also: ['汪汪队', '能行', '我们'], audioZh: 'audio/pups/finale-pups-radio.wav' },
      },
      {
        id: 'pups-rescue',
        title: '大救援', titleEn: 'The Big Rescue', emoji: '🚁', sticker: '🎖️',
        bg: 'linear-gradient(180deg,#81d4fa,#4fc3f7)', deco: '🚁🌲',
        intro: { en: "The kitten is stuck in a tall tree! Guide Skye's helicopter with Chinese words — up, down, left, right!", zh: '小猫被困在大树上！用中文指挥天天的直升机，上，下，左，右！', audioZh: 'audio/pups/intro-pups-rescue.wav' },
        audioComplete: 'audio/pups/complete-pups-rescue.wav',
        words: [
          { hanzi: '大', pinyin: 'dà', en: 'big', emoji: '🐘', also: ['打', '答'], audioZh: 'audio/pups/da.wav' },
          { hanzi: '小', pinyin: 'xiǎo', en: 'small', emoji: '🐭', also: ['笑', '校'], audioZh: 'audio/pups/xiao.wav' },
          { hanzi: '上', pinyin: 'shàng', en: 'up', emoji: '⬆️', also: ['伤', '商'], audioZh: 'audio/pups/shang.wav' },
          { hanzi: '下', pinyin: 'xià', en: 'down', emoji: '⬇️', also: ['吓', '夏'], audioZh: 'audio/pups/xia.wav' },
          { hanzi: '左', pinyin: 'zuǒ', en: 'left', emoji: '⬅️', also: ['做', '坐', '昨'], audioZh: 'audio/pups/zuo.wav' },
          { hanzi: '右', pinyin: 'yòu', en: 'right', emoji: '➡️', also: ['有', '又', '由'], audioZh: 'audio/pups/you.wav' },
        ],
        finale: { hanzi: '我们救了小猫！', pinyin: 'wǒ men jiù le xiǎo māo!', en: 'We saved the kitten!', emoji: '🏆', also: ['救了', '小猫', '我们'], audioZh: 'audio/pups/finale-pups-rescue.wav' },
      },
      {
        id: 'pups-hero',
        title: '小英雄', titleEn: 'Little Hero', emoji: '🦸', sticker: '🦸',
        bg: 'linear-gradient(180deg,#ffd54f,#4fc3f7)', deco: '🦸🏆',
        intro: { en: 'The kitten is safe! Celebrate the rescue with proud, whole sentences.', zh: '小猫得救啦！用自豪的整句话庆祝这次救援吧！', audioZh: 'audio/pups/intro-pups-hero.wav' },
        words: [
          { hanzi: '我们救了小猫', pinyin: 'wǒ men jiù le xiǎo māo', en: 'we saved the kitten', emoji: '🐱', also: ['救了', '小猫', '我们'], audioZh: 'audio/pups/wo-men-jiu-le-xiao-mao.wav' },
          { hanzi: '我今天很开心', pinyin: 'wǒ jīn tiān hěn kāi xīn', en: "I'm so happy today", emoji: '😊', also: ['开心', '今天', '很'], audioZh: 'audio/pups/wo-jin-tian-hen-kai-xin.wav' },
          { hanzi: '谢谢汪汪队', pinyin: 'xiè xie wāng wāng duì', en: 'thank you, puppy squad', emoji: '🐕', also: ['汪汪队', '谢谢'], audioZh: 'audio/pups/xie-xie-wang-wang-dui.wav' },
          { hanzi: '我是小英雄', pinyin: 'wǒ shì xiǎo yīng xióng', en: "I'm a little hero", emoji: '🦸', also: ['英雄', '小英雄', '我是'], audioZh: 'audio/pups/wo-shi-xiao-ying-xiong.wav' },
          { hanzi: '小猫谢谢你', pinyin: 'xiǎo māo xiè xie nǐ', en: 'the kitten thanks you', emoji: '🐱', also: ['谢谢', '小猫'], audioZh: 'audio/pups/xiao-mao-xie-xie-ni.wav' },
        ],
        finale: { hanzi: '我们是最棒的！', pinyin: 'wǒ men shì zuì bàng de!', en: "We're the best!", emoji: '🏆', also: ['最棒', '我们', '棒'], audioZh: 'audio/pups/finale-pups-hero.wav' },
      },
    ],
  },

  /* ==================== STORY 3: THE PRINCESS'S CROWN ==================== */
  {
    id: 'princess',
    title: '小公主的皇冠',
    titleEn: "The Princess's Crown",
    tagline: 'A magic wind scattered the crown jewels! Speak kind Chinese words to win them back.',
    hero: { name: '小公主', emoji: '👸', img: 'princess icon.png' },
    ending: { zh: '皇冠完成了！你是最棒的小公主！', en: 'The crown is complete! The kingdom cheers — and the dragon is your friend forever!', audioZh: 'audio/princess/ending-princess.wav' },
    chapters: [
      {
        id: 'princess-palace',
        title: '皇宫', titleEn: 'The Palace', emoji: '🏰', sticker: '💎',
        bg: 'linear-gradient(180deg,#f8bbd0,#fce4ec)', deco: '🏰✨',
        intro: { en: 'The palace doors are sealed by magic! Only polite words can open them. Say each one in Chinese!', zh: '皇宫的门被魔法锁住了！只有礼貌的话才能打开，说说看吧！', audioZh: 'audio/princess/intro-princess-palace.wav' },
        audioComplete: 'audio/princess/complete-princess-palace.wav',
        words: [
          { hanzi: '你好', pinyin: 'nǐ hǎo', en: 'hello', emoji: '👋', also: [], audioZh: 'audio/princess/ni-hao.wav' },
          { hanzi: '请', pinyin: 'qǐng', en: 'please', emoji: '🤲', also: ['清', '情'], audioZh: 'audio/princess/qing.wav' },
          { hanzi: '谢谢', pinyin: 'xiè xie', en: 'thank you', emoji: '🙏', also: [], audioZh: 'audio/princess/xie-xie.wav' },
          { hanzi: '对不起', pinyin: 'duì bu qǐ', en: 'sorry', emoji: '😔', also: ['对不', '对'], audioZh: 'audio/princess/dui-bu-qi.wav' },
          { hanzi: '没关系', pinyin: 'méi guān xi', en: "it's okay", emoji: '🤗', also: ['没关', '关系'], audioZh: 'audio/princess/mei-guan-xi.wav' },
          { hanzi: '公主', pinyin: 'gōng zhǔ', en: 'princess', emoji: '👸', also: ['宫主'], audioZh: 'audio/princess/gong-zhu.wav' },
        ],
        finale: { hanzi: '谢谢你，小公主！', pinyin: 'xiè xie nǐ, xiǎo gōng zhǔ!', en: 'Thank you, little princess!', emoji: '💎', also: ['谢谢你', '小公主', '公主'], audioZh: 'audio/princess/finale-princess-palace.wav' },
      },
      {
        id: 'princess-wardrobe',
        title: '魔法衣橱', titleEn: 'Magic Wardrobe', emoji: '👗', sticker: '👗',
        bg: 'linear-gradient(180deg,#e1bee7,#f3e5f5)', deco: '🪞🎀',
        intro: { en: 'Time to dress up for the royal ball! Say each item in Chinese and it flies out of the magic wardrobe.', zh: '该为皇家舞会打扮啦！说出每样东西，它就会从魔法衣橱里飞出来！', audioZh: 'audio/princess/intro-princess-wardrobe.wav' },
        audioComplete: 'audio/princess/complete-princess-wardrobe.wav',
        words: [
          { hanzi: '裙子', pinyin: 'qún zi', en: 'dress', emoji: '👗', also: ['群', '裙'], audioZh: 'audio/princess/qun-zi.wav' },
          { hanzi: '鞋子', pinyin: 'xié zi', en: 'shoes', emoji: '👠', also: ['鞋', '写字'], audioZh: 'audio/princess/xie-zi.wav' },
          { hanzi: '帽子', pinyin: 'mào zi', en: 'hat', emoji: '👒', also: ['帽', '毛'], audioZh: 'audio/princess/mao-zi.wav' },
          { hanzi: '王冠', pinyin: 'wáng guān', en: 'crown', emoji: '👑', also: ['王', '冠', '皇冠'], audioZh: 'audio/princess/wang-guan.wav' },
          { hanzi: '手套', pinyin: 'shǒu tào', en: 'gloves', emoji: '🧤', also: ['手', '套'], audioZh: 'audio/princess/shou-tao.wav' },
          { hanzi: '项链', pinyin: 'xiàng liàn', en: 'necklace', emoji: '📿', also: ['项', '链'], audioZh: 'audio/princess/xiang-lian.wav' },
        ],
        finale: { hanzi: '我爱我的裙子！', pinyin: 'wǒ ài wǒ de qún zi!', en: 'I love my dress!', emoji: '💃', also: ['裙子', '我的裙子'], audioZh: 'audio/princess/finale-princess-wardrobe.wav' },
      },
      {
        id: 'princess-dressup',
        title: '打扮', titleEn: 'Dress Up', emoji: '💄', sticker: '💄',
        bg: 'linear-gradient(180deg,#f8d3ff,#fff0f6)', deco: '💄🎀',
        intro: { en: 'Get ready for the ball! Put words together — say what to wear.', zh: '准备去舞会啦！把词连起来，说说要穿什么。', audioZh: 'audio/princess/intro-princess-dressup.wav' },
        audioComplete: 'audio/princess/complete-princess-dressup.wav',
        words: [
          { hanzi: '穿裙子', pinyin: 'chuān qún zi', en: 'wear a dress', emoji: '👗', also: ['裙子', '穿'], audioZh: 'audio/princess/chuan-qun-zi.wav' },
          { hanzi: '戴王冠', pinyin: 'dài wáng guān', en: 'wear the crown', emoji: '👑', also: ['王冠', '戴', '皇冠'], audioZh: 'audio/princess/dai-wang-guan.wav' },
          { hanzi: '穿鞋子', pinyin: 'chuān xié zi', en: 'put on shoes', emoji: '👠', also: ['鞋子', '穿'], audioZh: 'audio/princess/chuan-xie-zi.wav' },
          { hanzi: '红裙子', pinyin: 'hóng qún zi', en: 'red dress', emoji: '👗', also: ['裙子', '红'], audioZh: 'audio/princess/hong-qun-zi.wav' },
          { hanzi: '漂亮帽子', pinyin: 'piào liang mào zi', en: 'pretty hat', emoji: '👒', also: ['帽子', '漂亮'], audioZh: 'audio/princess/piao-liang-mao-zi.wav' },
          { hanzi: '戴项链', pinyin: 'dài xiàng liàn', en: 'wear a necklace', emoji: '📿', also: ['项链', '戴'], audioZh: 'audio/princess/dai-xiang-lian.wav' },
        ],
        finale: { hanzi: '我要穿红裙子！', pinyin: 'wǒ yào chuān hóng qún zi!', en: 'I want to wear the red dress!', emoji: '👗', also: ['红裙子', '裙子', '我要'], audioZh: 'audio/princess/finale-princess-dressup.wav' },
      },
      {
        id: 'princess-mirror',
        title: '魔镜', titleEn: 'Magic Mirror', emoji: '🪞', sticker: '🪞',
        bg: 'linear-gradient(180deg,#d1c4e9,#ede7f6)', deco: '🪞⭐',
        intro: { en: 'The magic mirror wants to meet you! Say each body part in Chinese and it lights up with sparkles.', zh: '魔镜想认识你！说出身体部位，它就会亮闪闪！', audioZh: 'audio/princess/intro-princess-mirror.wav' },
        audioComplete: 'audio/princess/complete-princess-mirror.wav',
        words: [
          { hanzi: '头', pinyin: 'tóu', en: 'head', emoji: '🙂', also: ['投', '偷'], audioZh: 'audio/princess/tou.wav' },
          { hanzi: '眼睛', pinyin: 'yǎn jing', en: 'eyes', emoji: '👀', also: ['眼', '眼镜'], audioZh: 'audio/princess/yan-jing.wav' },
          { hanzi: '耳朵', pinyin: 'ěr duo', en: 'ears', emoji: '👂', also: ['耳', '二朵'], audioZh: 'audio/princess/er-duo.wav' },
          { hanzi: '鼻子', pinyin: 'bí zi', en: 'nose', emoji: '👃', also: ['鼻', '笔'], audioZh: 'audio/princess/bi-zi.wav' },
          { hanzi: '嘴巴', pinyin: 'zuǐ ba', en: 'mouth', emoji: '👄', also: ['嘴', '最'], audioZh: 'audio/princess/zui-ba.wav' },
          { hanzi: '手', pinyin: 'shǒu', en: 'hands', emoji: '🤲', also: ['首', '受'], audioZh: 'audio/princess/shou.wav' },
          { hanzi: '脚', pinyin: 'jiǎo', en: 'feet', emoji: '🦶', also: ['角', '叫'], audioZh: 'audio/princess/jiao.wav' },
        ],
        finale: { hanzi: '我的眼睛大大的！', pinyin: 'wǒ de yǎn jing dà dà de!', en: 'My eyes are so big!', emoji: '✨', also: ['眼睛', '大大的'], audioZh: 'audio/princess/finale-princess-mirror.wav' },
      },
      {
        id: 'princess-inmirror',
        title: '照镜子', titleEn: 'In the Mirror', emoji: '💫', sticker: '💫',
        bg: 'linear-gradient(180deg,#d1c4e9,#f3e5f5)', deco: '💫🪞',
        intro: { en: 'Look in the magic mirror and describe yourself — in whole sentences!', zh: '照照魔镜，用整句话说说你自己吧！', audioZh: 'audio/princess/intro-princess-inmirror.wav' },
        audioComplete: 'audio/princess/complete-princess-inmirror.wav',
        words: [
          { hanzi: '我有两只眼睛', pinyin: 'wǒ yǒu liǎng zhī yǎn jing', en: 'I have two eyes', emoji: '👀', also: ['眼睛', '两只', '我有'], audioZh: 'audio/princess/wo-you-liang-zhi-yan-jing.wav' },
          { hanzi: '我的头发很长', pinyin: 'wǒ de tóu fa hěn cháng', en: 'my hair is long', emoji: '💇', also: ['头发', '很长', '长'], audioZh: 'audio/princess/wo-de-tou-fa-hen-chang.wav' },
          { hanzi: '我今天很漂亮', pinyin: 'wǒ jīn tiān hěn piào liang', en: 'I look pretty today', emoji: '✨', also: ['漂亮', '今天'], audioZh: 'audio/princess/wo-jin-tian-hen-piao-liang.wav' },
          { hanzi: '这是我的手', pinyin: 'zhè shì wǒ de shǒu', en: 'this is my hand', emoji: '🤲', also: ['我的手', '手'], audioZh: 'audio/princess/zhe-shi-wo-de-shou.wav' },
          { hanzi: '我笑得很开心', pinyin: 'wǒ xiào de hěn kāi xīn', en: 'I smile happily', emoji: '😊', also: ['开心', '笑'], audioZh: 'audio/princess/wo-xiao-de-hen-kai-xin.wav' },
        ],
        finale: { hanzi: '镜子里的我真美！', pinyin: 'jìng zi lǐ de wǒ zhēn měi!', en: 'I look beautiful in the mirror!', emoji: '🪞', also: ['真美', '镜子', '美'], audioZh: 'audio/princess/finale-princess-inmirror.wav' },
      },
      {
        id: 'princess-teaparty',
        title: '皇家茶会', titleEn: 'Royal Tea Party', emoji: '🫖', sticker: '🍰',
        bg: 'linear-gradient(180deg,#ffe0f0,#fff3e0)', deco: '🫖🧚',
        intro: { en: 'The fairies are coming for tea! Say each treat in Chinese to set the royal table.', zh: '小仙女们要来喝茶啦！说出每样点心，摆好皇家餐桌！', audioZh: 'audio/princess/intro-princess-teaparty.wav' },
        audioComplete: 'audio/princess/complete-princess-teaparty.wav',
        words: [
          { hanzi: '茶', pinyin: 'chá', en: 'tea', emoji: '🍵', also: ['查', '差'], audioZh: 'audio/princess/cha.wav' },
          { hanzi: '蛋糕', pinyin: 'dàn gāo', en: 'cake', emoji: '🍰', also: ['蛋', '糕'], audioZh: 'audio/princess/dan-gao.wav' },
          { hanzi: '饼干', pinyin: 'bǐng gān', en: 'cookie', emoji: '🍪', also: ['饼', '干'], audioZh: 'audio/princess/bing-gan.wav' },
          { hanzi: '糖果', pinyin: 'táng guǒ', en: 'candy', emoji: '🍬', also: ['糖'], audioZh: 'audio/princess/tang-guo.wav' },
          { hanzi: '草莓', pinyin: 'cǎo méi', en: 'strawberry', emoji: '🍓', also: ['草', '莓'], audioZh: 'audio/princess/cao-mei.wav' },
          { hanzi: '果汁', pinyin: 'guǒ zhī', en: 'juice', emoji: '🧃', also: ['果', '汁'], audioZh: 'audio/princess/guo-zhi.wav' },
        ],
        finale: { hanzi: '请喝茶！', pinyin: 'qǐng hē chá!', en: 'Please have some tea!', emoji: '🫖', also: ['喝茶', '请喝'], audioZh: 'audio/princess/finale-princess-teaparty.wav' },
      },
      {
        id: 'princess-serving',
        title: '请客', titleEn: 'Serving Guests', emoji: '🧁', sticker: '🧁',
        bg: 'linear-gradient(180deg,#ffe0f0,#fff8e1)', deco: '🧁🫖',
        intro: { en: 'Be a kind host! Ask for and offer treats in full sentences.', zh: '做个热情的小主人！用整句话点心、请客。', audioZh: 'audio/princess/intro-princess-serving.wav' },
        audioComplete: 'audio/princess/complete-princess-serving.wav',
        words: [
          { hanzi: '我要蛋糕', pinyin: 'wǒ yào dàn gāo', en: 'I want cake', emoji: '🍰', also: ['蛋糕', '我要'], audioZh: 'audio/princess/wo-yao-dan-gao.wav' },
          { hanzi: '请喝茶', pinyin: 'qǐng hē chá', en: 'please have tea', emoji: '🍵', also: ['喝茶', '茶'], audioZh: 'audio/princess/qing-he-cha.wav' },
          { hanzi: '我想吃草莓', pinyin: 'wǒ xiǎng chī cǎo méi', en: "I'd like strawberries", emoji: '🍓', also: ['草莓', '想吃'], audioZh: 'audio/princess/wo-xiang-chi-cao-mei.wav' },
          { hanzi: '给你果汁', pinyin: 'gěi nǐ guǒ zhī', en: "here's juice for you", emoji: '🧃', also: ['果汁', '给你'], audioZh: 'audio/princess/gei-ni-guo-zhi.wav' },
          { hanzi: '蛋糕真好吃', pinyin: 'dàn gāo zhēn hǎo chī', en: 'the cake is yummy', emoji: '🍰', also: ['蛋糕', '好吃'], audioZh: 'audio/princess/dan-gao-zhen-hao-chi.wav' },
        ],
        finale: { hanzi: '请大家吃蛋糕！', pinyin: 'qǐng dà jiā chī dàn gāo!', en: 'Everyone, please have cake!', emoji: '🎂', also: ['蛋糕', '大家', '吃'], audioZh: 'audio/princess/finale-princess-serving.wav' },
      },
      {
        id: 'princess-dragon',
        title: '友好的龙', titleEn: 'The Friendly Dragon', emoji: '🐉', sticker: '🐉',
        bg: 'linear-gradient(180deg,#b39ddb,#ffccbc)', deco: '🐉🌋',
        intro: { en: 'A lonely dragon guards the last jewel. Name his feelings in Chinese to show him you understand — and become friends!', zh: '孤单的龙守着最后一颗宝石。说出他的心情，和他做朋友吧！', audioZh: 'audio/princess/intro-princess-dragon.wav' },
        audioComplete: 'audio/princess/complete-princess-dragon.wav',
        words: [
          { hanzi: '开心', pinyin: 'kāi xīn', en: 'happy', emoji: '😊', also: ['开', '心'], audioZh: 'audio/princess/kai-xin.wav' },
          { hanzi: '难过', pinyin: 'nán guò', en: 'sad', emoji: '😢', also: ['难'], audioZh: 'audio/princess/nan-guo.wav' },
          { hanzi: '累', pinyin: 'lèi', en: 'tired', emoji: '😴', also: ['泪', '雷', '类'], audioZh: 'audio/princess/lei.wav' },
          { hanzi: '饿', pinyin: 'è', en: 'hungry', emoji: '😋', also: ['恶', '鹅'], audioZh: 'audio/princess/e.wav' },
          { hanzi: '怕', pinyin: 'pà', en: 'scared', emoji: '😨', also: ['爬', '趴'], audioZh: 'audio/princess/pa.wav' },
          { hanzi: '爱', pinyin: 'ài', en: 'love', emoji: '❤️', also: ['艾', '矮'], audioZh: 'audio/princess/ai.wav' },
        ],
        finale: { hanzi: '我们是好朋友！', pinyin: 'wǒ men shì hǎo péng you!', en: 'We are best friends!', emoji: '🥹', also: ['好朋友', '朋友', '我们是'], audioZh: 'audio/princess/finale-princess-dragon.wav' },
      },
      {
        id: 'princess-ball',
        title: '皇家舞会', titleEn: 'Ball & Coronation', emoji: '👑', sticker: '👑',
        bg: 'linear-gradient(180deg,#ffd6f0,#d1c4ff)', deco: '👑🎊',
        intro: { en: 'The crown is whole again — time for the royal ball! Celebrate with big, happy sentences.', zh: '皇冠修好啦——皇家舞会开始！用又长又开心的句子一起庆祝吧！', audioZh: 'audio/princess/intro-princess-ball.wav' },
        words: [
          { hanzi: '我们一起跳舞', pinyin: 'wǒ men yì qǐ tiào wǔ', en: "let's dance together", emoji: '💃', also: ['跳舞', '一起', '我们'], audioZh: 'audio/princess/wo-men-yi-qi-tiao-wu.wav' },
          { hanzi: '今天真开心', pinyin: 'jīn tiān zhēn kāi xīn', en: 'today is so happy', emoji: '😊', also: ['开心', '今天', '真'], audioZh: 'audio/princess/jin-tian-zhen-kai-xin.wav' },
          { hanzi: '你跳得真好', pinyin: 'nǐ tiào de zhēn hǎo', en: 'you dance so well', emoji: '🩰', also: ['跳', '真好', '你'], audioZh: 'audio/princess/ni-tiao-de-zhen-hao.wav' },
          { hanzi: '我是小公主', pinyin: 'wǒ shì xiǎo gōng zhǔ', en: "I'm the little princess", emoji: '👸', also: ['公主', '小公主', '我是'], audioZh: 'audio/princess/wo-shi-xiao-gong-zhu.wav' },
          { hanzi: '谢谢大家来', pinyin: 'xiè xie dà jiā lái', en: 'thank you all for coming', emoji: '🎉', also: ['谢谢', '大家'], audioZh: 'audio/princess/xie-xie-da-jia-lai.wav' },
        ],
        finale: { hanzi: '我爱你们，谢谢！', pinyin: 'wǒ ài nǐ men, xiè xie!', en: 'I love you all, thank you!', emoji: '💗', also: ['我爱', '你们', '谢谢'], audioZh: 'audio/princess/finale-princess-ball.wav' },
      },
    ],
  },
];
